<?php

declare(strict_types=1);

namespace Fmos\Domains\Furniture;

/**
 * Module-type metadata layered on FurnitureTemplateCatalog codes.
 * Does not replace templates — extends them with internal-config allow-lists.
 */
final class ModuleTypeCatalog
{
    /**
     * @return array<string, array<string,mixed>>
     */
    public static function all(): array
    {
        $templates = FurnitureTemplateCatalog::all();
        $meta = self::metaByCode();
        $out = [];
        foreach ($templates as $code => $tpl) {
            $m = $meta[$code] ?? [
                'allowed_config_ids' => ['CFG_SHELVES', 'CFG_DRAWERS', 'CFG_OPEN'],
                'recommended_config_ids' => ['CFG_SHELVES'],
                'optional_config_ids' => ['CFG_DRAWERS', 'CFG_OPEN'],
                'required_config_ids' => [],
                'structural_notes' => 'Carcass (sides/top/bottom/back) always generated by LayoutEngine.',
            ];
            $out[$code] = [
                'id' => $code,
                'template_code' => $code,
                'name' => $tpl['name'],
                'category' => $tpl['category'],
                'description' => $tpl['description'],
                'parameters' => $tpl['parameters'],
                'allowed_config_ids' => $m['allowed_config_ids'],
                'recommended_config_ids' => $m['recommended_config_ids'],
                'optional_config_ids' => $m['optional_config_ids'],
                'required_config_ids' => $m['required_config_ids'],
                'structural_notes' => $m['structural_notes'],
            ];
        }
        return $out;
    }

    /** @return array<string,mixed>|null */
    public static function get(string $templateCode): ?array
    {
        $all = self::all();
        return $all[$templateCode] ?? null;
    }

    /**
     * @return array<string, array{
     *   allowed_config_ids:list<string>,
     *   recommended_config_ids:list<string>,
     *   optional_config_ids:list<string>,
     *   required_config_ids:list<string>,
     *   structural_notes:string
     * }>
     */
    private static function metaByCode(): array
    {
        $wardrobe = [
            'allowed_config_ids' => [
                'CFG_HANGING', 'CFG_SHELVES', 'CFG_DRAWERS', 'CFG_OPEN', 'CFG_MIRROR',
                'CFG_HANGING_LONG', 'CFG_SHOE',
            ],
            'recommended_config_ids' => ['CFG_HANGING', 'CFG_SHELVES'],
            'optional_config_ids' => ['CFG_DRAWERS', 'CFG_MIRROR', 'CFG_OPEN', 'CFG_HANGING_LONG', 'CFG_SHOE'],
            'required_config_ids' => [],
            'structural_notes' => 'Carcass panels required. Internals are advisory; user may override.',
        ];

        $kitchenBase = [
            'allowed_config_ids' => [
                'CFG_KB_SHELF', 'CFG_KB_DRAWERS', 'CFG_KB_SINK', 'CFG_SHELVES', 'CFG_DRAWERS', 'CFG_OPEN',
                'CFG_KB_PLATE_TRAY', 'CFG_KB_CUTLERY', 'CFG_KB_BOTTLE', 'CFG_KB_WASTE',
            ],
            'recommended_config_ids' => ['CFG_KB_SHELF'],
            'optional_config_ids' => [
                'CFG_KB_DRAWERS', 'CFG_KB_SINK', 'CFG_KB_PLATE_TRAY', 'CFG_KB_CUTLERY',
                'CFG_KB_BOTTLE', 'CFG_KB_WASTE',
            ],
            'required_config_ids' => [],
            'structural_notes' => 'Carcass + plinth from LayoutEngine. Specialty kitchen configs may be catalog stubs until implemented.',
        ];

        return [
            'WARDROBE' => $wardrobe,
            'WARDROBE_SLIDING' => $wardrobe,
            'WARDROBE_LOFT' => $wardrobe,
            'KITCHEN_BASE' => $kitchenBase,
            'KITCHEN_CORNER' => [
                'allowed_config_ids' => ['CFG_KB_SHELF', 'CFG_SHELVES', 'CFG_OPEN', 'CFG_KB_PLATE_TRAY'],
                'recommended_config_ids' => ['CFG_KB_SHELF'],
                'optional_config_ids' => ['CFG_OPEN'],
                'required_config_ids' => [],
                'structural_notes' => 'Blind corner carcass; specialty corner hardware not modeled yet.',
            ],
            'KITCHEN_WALL' => [
                'allowed_config_ids' => ['CFG_SHELVES', 'CFG_OPEN', 'CFG_DRAWERS'],
                'recommended_config_ids' => ['CFG_SHELVES'],
                'optional_config_ids' => ['CFG_OPEN', 'CFG_DRAWERS'],
                'required_config_ids' => [],
                'structural_notes' => 'Wall cabinet carcass; no plinth typical.',
            ],
            'KITCHEN_TALL' => [
                'allowed_config_ids' => ['CFG_SHELVES', 'CFG_DRAWERS', 'CFG_OPEN', 'CFG_HANGING'],
                'recommended_config_ids' => ['CFG_SHELVES'],
                'optional_config_ids' => ['CFG_DRAWERS', 'CFG_OPEN'],
                'required_config_ids' => [],
                'structural_notes' => 'Tall pantry / appliance tower; appliance cutouts not yet parametric.',
            ],
            'TV_UNIT' => [
                'allowed_config_ids' => ['CFG_OPEN', 'CFG_DRAWERS', 'CFG_SHELVES'],
                'recommended_config_ids' => ['CFG_OPEN'],
                'optional_config_ids' => ['CFG_DRAWERS', 'CFG_SHELVES'],
                'required_config_ids' => [],
                'structural_notes' => 'Low media unit.',
            ],
            'CHEST_DRAWERS' => [
                'allowed_config_ids' => ['CFG_DRAWERS'],
                'recommended_config_ids' => ['CFG_DRAWERS'],
                'optional_config_ids' => [],
                'required_config_ids' => [],
                'structural_notes' => 'Drawer chest; door_type typically NONE.',
            ],
            'BOOKCASE' => [
                'allowed_config_ids' => ['CFG_SHELVES', 'CFG_OPEN'],
                'recommended_config_ids' => ['CFG_SHELVES'],
                'optional_config_ids' => ['CFG_OPEN'],
                'required_config_ids' => [],
                'structural_notes' => 'Open shelving.',
            ],
            'CROCKERY' => [
                'allowed_config_ids' => ['CFG_SHELVES', 'CFG_DRAWERS', 'CFG_OPEN'],
                'recommended_config_ids' => ['CFG_SHELVES'],
                'optional_config_ids' => ['CFG_DRAWERS', 'CFG_OPEN'],
                'required_config_ids' => [],
                'structural_notes' => 'Display + storage.',
            ],
            'VANITY' => [
                'allowed_config_ids' => ['CFG_DRAWERS', 'CFG_SHELVES', 'CFG_OPEN', 'CFG_KB_SINK'],
                'recommended_config_ids' => ['CFG_DRAWERS'],
                'optional_config_ids' => ['CFG_SHELVES', 'CFG_OPEN'],
                'required_config_ids' => [],
                'structural_notes' => 'Bathroom vanity; plumbing specialty deferred.',
            ],
            'STUDY_TABLE' => [
                'allowed_config_ids' => ['CFG_DRAWERS', 'CFG_SHELVES', 'CFG_OPEN'],
                'recommended_config_ids' => ['CFG_DRAWERS'],
                'optional_config_ids' => ['CFG_SHELVES', 'CFG_OPEN'],
                'required_config_ids' => [],
                'structural_notes' => 'Desk with optional side storage.',
            ],
        ];
    }
}
